name: Publish
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      # - run: npm test
      - run: npm run build
      - run: npm run package
    # - uses: trmcnvn/chrome-addon@v3
    #   with:
    #     extension: chrome-meet-webhook-extension
    #     zip: dist/chrome-meet-webhook-extension.zip
    #     client-id: ${{ secrets.CHROME_WEBSTORE__CLIENT_ID }}
    #     client-secret: ${{ secrets.CHROME_WEBSTORE__CLIENT_SECRET }}
    #     refresh-token: ${{ secrets.CHROME_WEBSTORE_REFRESH_TOKEN }}
    #     publishTarget: trustedTesters